# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

mobile_base_controller:
  type        : sd_control/ThreeOmniWheelsDriveController
  left_wheel  : 'left_wheel_to_base'
  right_wheel : 'right_wheel_to_base'
  back_wheel : 'back_wheel_to_base'

  publish_rate: 50.0               # default: 50
  publish_cmd: true
  enable_odom_tf: false
  open_loop: false
  
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Distance between the wheel and the robot center
  wheel_to_center : 0.175

  # Wheel radius
  wheel_radius : 0.029

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id (default: base_link)
  base_frame_id: 'r1/base_link'
  odom_frame_id: 'r1/odom'

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # m/s^2
      has_jerk_limits        : false
    y:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # m/s^2
      has_jerk_limits        : false
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 6.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 9.0  # rad/s^2
      has_jerk_limits        : false
